//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;RSAKeyValue&gt;&lt;Modulus&gt;t+qBow+Cwh6O0yNUtOIR/PW8XvKWEfxz2yeKOzyiMbEIpldyI50aGF05/QlPhGuoFr6QyR4a5bVsyX5eduro9/mLrs9SnYai0nlCR/rwmMf+G1pvRF45LgDj/GefNj9iCWDarS0qcpgl3BxxOEgCgHMpVBXeZpdlqL250qTUL50=&lt;/Modulus&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;&lt;P&gt;9Go3IDnt0zfp1/339qO+nH33agJ4S22RRwpIsVgXPmGVcagfJyI9ASXZSVrnf/IB1sTcH1GvVND03Cj+THHLxw==&lt;/P&gt;&lt;Q&gt;wKIvNv6rkK1hv7wHjOdEdF1IhEiLDmSahiBNAmXwyZ7ZDEEFJNMAzZ4/ZEP28wUy4mvgRWcS7rGM70XHqciBew==&lt;/Q&gt;&lt;DP&gt;1MwBMNKeyG3+76nTkO4hj5hwp+B8oZdEjChc/+KlYg+OEIWCkgzSNkSguKgntBKdHUMKL05sK5k+Bsy+Ewpkkw==&lt; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string _private {
            get {
                return ResourceManager.GetString("_private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;RSAKeyValue&gt;&lt;Modulus&gt;t+qBow+Cwh6O0yNUtOIR/PW8XvKWEfxz2yeKOzyiMbEIpldyI50aGF05/QlPhGuoFr6QyR4a5bVsyX5eduro9/mLrs9SnYai0nlCR/rwmMf+G1pvRF45LgDj/GefNj9iCWDarS0qcpgl3BxxOEgCgHMpVBXeZpdlqL250qTUL50=&lt;/Modulus&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;&lt;/RSAKeyValue&gt;.
        /// </summary>
        internal static string _public {
            get {
                return ResourceManager.GetString("_public", resourceCulture);
            }
        }
    }
}
