//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace детский_дом.ui.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("детский_дом.ui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;RSAKeyValue&gt;&lt;Modulus&gt;uPteeQnHYhGfizWRhV00QzGGGhzCTwqKuoKEvGO0ahPFw+1f8Pi3zcDeGHhG6boQZnWbLWnhkwawTMlSdqfIKY6xSXy89I1cVMNdYZqQZY7cL9HecxczmYffpNqGQDEEOFFUbv4n95PPqno5hIjy7DwBkuRyzHDvVOvadzpY4IE=&lt;/Modulus&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;&lt;P&gt;1KBFvvx4efWlzknMNbJRZy+/DE44bHV2qnzPbX+/w84dQ0ZL7LJAqdZRazGYQ73lB/lxT7fL1dJrjarzyyAmdw==&lt;/P&gt;&lt;Q&gt;3rd3s3b82SlX97Zv0IymXSkahx9VXR9xh21giN8usVYUK2b4eoEb7Vd1XUW1GYx690oo6BvSVDuYXYziTMlWxw==&lt;/Q&gt;&lt;DP&gt;khWHtd86Wvi2MVQstJvOJ+n7BdZcF9BgdmQIE8BYnYvoOQd8NKSHnuh7yf0qEyjNybvM6StrJX5LnOreUynEow==&lt; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string _private {
            get {
                return ResourceManager.GetString("_private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;RSAKeyValue&gt;&lt;Modulus&gt;uPteeQnHYhGfizWRhV00QzGGGhzCTwqKuoKEvGO0ahPFw+1f8Pi3zcDeGHhG6boQZnWbLWnhkwawTMlSdqfIKY6xSXy89I1cVMNdYZqQZY7cL9HecxczmYffpNqGQDEEOFFUbv4n95PPqno5hIjy7DwBkuRyzHDvVOvadzpY4IE=&lt;/Modulus&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;&lt;/RSAKeyValue&gt;.
        /// </summary>
        internal static string _public {
            get {
                return ResourceManager.GetString("_public", resourceCulture);
            }
        }
    }
}
